INSERT INTO Defines(Name, Value) VALUES('OPINION_WEIGHT_CAPTURED_RELIGION', 80);

--GLOBAL_CS_GIFTS
INSERT INTO Defines(Name, Value) VALUES('MINOR_CIV_FIRST_CONTACT_BONUS_FAITH', 4);
INSERT INTO Defines(Name, Value) VALUES('MINOR_CIV_FIRST_CONTACT_BONUS_CULTURE', 6);
INSERT INTO Defines(Name, Value) VALUES('MINOR_CIV_FIRST_CONTACT_BONUS_FOOD', 6);
INSERT INTO Defines(Name, Value) VALUES('MINOR_CIV_FIRST_CONTACT_BONUS_GOLD', 20);
INSERT INTO Defines(Name, Value) VALUES('MINOR_CIV_FIRST_CONTACT_BONUS_FRIENDSHIP', 20);
INSERT INTO Defines(Name, Value) VALUES('MINOR_CIV_FIRST_CONTACT_SUBSEQUENT_TEAM_MULTIPLIER', 1);
INSERT INTO Defines(Name, Value) VALUES('MINOR_CIV_FIRST_CONTACT_SUBSEQUENT_TEAM_DIVISOR', 2);
INSERT INTO Defines(Name, Value) VALUES('MINOR_CIV_FIRST_CONTACT_FRIENDLY_BONUS_MULTIPLIER', 5);
INSERT INTO Defines(Name, Value) VALUES('MINOR_CIV_FIRST_CONTACT_FRIENDLY_BONUS_DIVISOR', 4);
INSERT INTO Defines(Name, Value) VALUES('MINOR_CIV_FIRST_CONTACT_HOSTILE_BONUS_MULTIPLIER', 3);
INSERT INTO Defines(Name, Value) VALUES('MINOR_CIV_FIRST_CONTACT_HOSTILE_BONUS_DIVISOR', 4);