@echo off
SETLOCAL

set STATUS=Clean
for /f "usebackq delims=" %%i in (`git status --untracked-files^=no --porcelain`) do (
    if [%%i] NEQ [] (
        set STATUS=Dirty
        echo Uncommitted change^(s^): %%i
    )
)

if "%STATUS%" == "Clean" (echo Working tree is clean.)

for /f "usebackq delims=" %%i in (`git rev-parse --short HEAD`) do set COMMIT_HASH=%%i

for /f "usebackq delims=" %%i in (`git rev-parse --abbrev-ref HEAD`) do set BRANCH=%%i
set BRANCH=%BRANCH:/=_%
set BRANCH=%BRANCH: =_%

for /f "usebackq delims=" %%i in (`git config user.name`) do set USERNAME=%%i
if not defined USERNAME set USERNAME=%USERNAME%

for /f "usebackq delims=" %%i in (`git config --get remote.origin.url`) do (
    set REPO_OWNER=%%i
    :: Extract username/repo from GitHub/GitLab URL (e.g., https://github.com/user/repo.git → user-repo)
    for /f "tokens=4,5 delims=/." %%a in ("%%i") do set REPO_OWNER=%%a
)
if not defined REPO_OWNER (
    for /f "usebackq delims=" %%i in (`git rev-parse --show-toplevel`) do set REPO_OWNER=%%~nxi
)

set VERSION_STRING=%REPO_OWNER%_%BRANCH%_%USERNAME%_%COMMIT_HASH%_%STATUS%

echo const char CURRENT_GAMECORE_VERSION[] = "%VERSION_STRING%"; //autogenerated, do not commit this file! > %~dp0%commit_id.inc
echo Version identifier will be "%VERSION_STRING%"

ENDLOCAL