ALTER TABLE UnitPromotions ADD CanCrossIce INTEGER DEFAULT 0;
INSERT INTO CustomModDbUpdates(Name, Value) VALUES('PROMOTIONS_CROSS_ICE', 1);

ALTER TABLE UnitPromotions ADD CanCrossMountains INTEGER DEFAULT 0;
INSERT INTO CustomModDbUpdates(Name, Value) VALUES('PROMOTIONS_CROSS_MOUNTAINS', 1);

ALTER TABLE UnitPromotions ADD CanCrossOceans INTEGER DEFAULT 0;
INSERT INTO CustomModDbUpdates(Name, Value) VALUES('PROMOTIONS_CROSS_OCEANS', 1);