ALTER TABLE Processes ADD COLUMN 'DefenseValue' INTEGER DEFAULT 0;

INSERT INTO Defines(Name, Value) VALUES('ORIGINAL_CAPITAL_MODMAX', 10);

INSERT INTO Defines(Name, Value) VALUES('HEALTH_DISEASE_CONNECTION_MOD', 10);
INSERT INTO Defines(Name, Value) VALUES('HEALTH_DISEASE_TRADE_MOD',10);

INSERT INTO Defines(Name, Value) VALUES('FRESH_WATER_HEALTH_YIELD', 2);
INSERT INTO Defines(Name, Value) VALUES('BONUS_PER_ADJACENT_FRIEND_RANGED', 0);
INSERT INTO Defines(Name, Value) VALUES('VERY_UNHAPPY_DISEASE_PENALTY_PER_UNHAPPY', 2);
INSERT INTO Defines(Name, Value) VALUES('VERY_UNHAPPY_MAX_DISEASE_PENALTY', 100);
INSERT INTO Defines(Name, Value) VALUES('VERY_UNHAPPY_CRIME_PENALTY_PER_UNHAPPY', 2);
INSERT INTO Defines(Name, Value) VALUES('VERY_UNHAPPY_MAX_CRIME_PENALTY', 100);
INSERT INTO Defines(Name, Value) VALUES('AI_CITIZEN_VALUE_HEALTH', 7);

INSERT INTO Defines(Name, Value) VALUES('CITY_CRIME_SPY_YIELD', 6);
INSERT INTO Defines(Name, Value) VALUES('CITY_CRIME_OPINION_REVOLUTIONARY_WAVE_YIELD', 10);
INSERT INTO Defines(Name, Value) VALUES('CITY_CRIME_OPINION_CIVIL_RESISTANCE_YIELD', 4);
INSERT INTO Defines(Name, Value) VALUES('CITY_CRIME_OPINION_DISSIDENTS_YIELD', 1);
INSERT INTO Defines(Name, Value) VALUES('CITY_CRIME_GOLDEN_AGE_YIELD',-10);
INSERT INTO Defines(Name, Value) VALUES('CITY_LOYALTY_GOLDEN_AGE_YIELD', -10);

ALTER TABLE Features ADD PseudoNaturalWonder INTEGER DEFAULT 0;
ALTER TABLE Features ADD  'Volcano'  boolean default 0;


ALTER TABLE Traits ADD COLUMN 'NoResistance'  BOOLEAN DEFAULT 0;
ALTER TABLE Traits ADD COLUMN 'GoldenAgeOnWar' BOOLEAN DEFAULT 0;
ALTER TABLE Traits ADD COLUMN 'BuyOwnedTiles' BOOLEAN DEFAULT 0;
ALTER TABLE Traits ADD COLUMN `CanPurchaseWonderInGoldenAge` BOOLEAN NOT NULL DEFAULT 0;

ALTER TABLE HandicapInfos ADD StrategicResourceMod INTEGER DEFAULT 100;
ALTER TABLE HandicapInfos ADD StrategicResourceModPerEra INTEGER DEFAULT 0;
-- If AIFirstProphetPercent is positive, it overrides AITrainPercent on AI's First Prophet Cost
ALTER TABLE HandicapInfos ADD AIFirstProphetPercent INTEGER DEFAULT 0;

ALTER TABLE GameSpeeds ADD FreePromotion TEXT DEFAULT NULL REFERENCES UnitPromotions(Type);
ALTER TABLE GameSpeeds ADD COLUMN 'SetterExtraPercent' INTEGER DEFAULT 0;

ALTER TABLE Projects ADD COLUMN 'FreePromotion' TEXT DEFAULT NULL REFERENCES UnitPromotions(Type);
ALTER TABLE Projects ADD COLUMN 'NoBroadcast' BOOLEAN DEFAULT 0;
ALTER TABLE Projects ADD COLUMN 'PolicyBranchPrereq' TEXT DEFAULT NULL REFERENCES PolicyBranchTypes(Type);
CREATE TABLE IF NOT EXISTS Project_PolicyNeeded (
    `ProjectType` TEXT DEFAULT '' references Projects(Type),
    `PolicyType` TEXT DEFAULT '' references Policies(Type)
);


ALTER TABLE Civilizations ADD COLUMN `SpecialGAText` TEXT DEFAULT 'TXT_KEY_GOLDEN_AGE_ANNOUNCE';
ALTER TABLE Civilizations ADD COLUMN `SpecialGAHelpText` TEXT DEFAULT 'TXT_KEY_TP_GOLDEN_AGE_EFFECT';

ALTER TABLE Builds ADD COLUMN 'ObsoleteTech' TEXT DEFAULT NULL;
CREATE TABLE IF NOT EXISTS Build_ResourceRemove (
    BuildType TEXT DEFAULT NULL  REFERENCES Builds(Type),
    ResourceType TEXT DEFAULT NULL REFERENCES Resources(Type)
);