-- API From VMC
ALTER TABLE Units ADD CannotEmbark INTEGER DEFAULT 0;
INSERT INTO CustomModDbUpdates(Name, Value) VALUES('GLOBAL_CANNOT_EMBARK', 1);

ALTER TABLE Units ADD NoMinorGifts INTEGER DEFAULT 0;
INSERT INTO CustomModDbUpdates(Name, Value) VALUES('GLOBAL_EXCLUDE_FROM_GIFTS', 1);

ALTER TABLE Units ADD MoveAfterUpgrade INTEGER DEFAULT 0;
INSERT INTO CustomModDbUpdates(Name, Value) VALUES('GLOBAL_MOVE_AFTER_UPGRADE', 1);

ALTER TABLE Units ADD PromotionClass TEXT DEFAULT NULL REFERENCES UnitCombatInfos(Type);
INSERT INTO CustomModDbUpdates(Name, Value) VALUES('GLOBAL_PROMOTION_CLASSES', 1);

ALTER TABLE Units ADD CanRepairFleet INTEGER DEFAULT 0;
ALTER TABLE Units ADD CanChangePort INTEGER DEFAULT 0;
INSERT INTO CustomModDbUpdates(Name, Value) VALUES('GLOBAL_SEPARATE_GREAT_ADMIRAL', 1);